-- return function()
--     local emitter = cc.ParticleSystemQuad:createWithTotalParticles(20)
--     emitter:setPosVar(cc.p(0, 0))
--     emitter:setDuration(-1)
--     emitter:setEmitterMode(0)
--     emitter:setPositionType(2)
--     emitter:setAngle(90)
--     emitter:setAngleVar(90)
--     emitter:setRotationIsDir(true)
--     emitter:setLife(0.3)
--     emitter:setLifeVar(0.2)
--     emitter:setStartSize(35)
--     emitter:setStartSizeVar(5)
--     emitter:setEndSize(10)
--     emitter:setGravity(cc.p(0,-500))
--     emitter:setSpeed(100)
--     emitter:setSpeedVar(20)
--     emitter:setStartSpin(0)
--     emitter:setStartSpinVar(100)
--     emitter:setEndSpin(0)
--     emitter:setEndSpinVar(0)
--     emitter:setStartColor(cc.c4f(1, 1, 1, 0.8))
--     emitter:setEndColor(cc.c4f(1, 1, 1, 0.1))
--     emitter:setBlendAdditive(true)
--     emitter:setEmissionRate(10)
--     emitter:setTexture(cc.Director:getInstance():getTextureCache():addImage("lt.png"))
--     emitter:updateWithNoTime()
--     return emitter
-- end


return function()
    local emitter = cc.ParticleSystemQuad:createWithTotalParticles(30)
    emitter:setPosVar(cc.p(25, 25))
    emitter:setDuration(-1)
    emitter:setEmitterMode(0)
    emitter:setPositionType(2)
    emitter:setAngleVar(360)
    emitter:setRotationIsDir(true)
    emitter:setLife(2)
    emitter:setLifeVar(0)
    emitter:setStartSize(35)
    emitter:setStartSizeVar(15)
    emitter:setEndSize(0)
    emitter:setGravity(cc.p(0,0))
    emitter:setSpeed(1)
    emitter:setSpeedVar(0)
    emitter:setStartSpin(0)
    emitter:setStartSpinVar(100)
    emitter:setEndSpin(0)
    emitter:setEndSpinVar(0)
    emitter:setStartColor(cc.c4f(1, 1, 1, 0.8))
    emitter:setEndColor(cc.c4f(1, 1, 1, 0.1))
    emitter:setEmissionRate(0.65)
    emitter:setBlendAdditive(true)
    emitter:setEmissionRate(4)
    emitter:setTexture(cc.Director:getInstance():getTextureCache():addImage("lt.png"))
    emitter:updateWithNoTime()
    return emitter
end
